spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?characterEncoding=utf8&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: root
server:
  port: 9090
mybatis:
  type-aliases-package: com.company.education.lecture, com.company.education.enrollment
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true